version: "3"
services:
  frontend:
    image: hsndocker/frontend:latest
    ports:
      - 3000:3000
    networks: 
      - engineerx 
    depends_on:
      - backend
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
         ./wait-for-it.sh backend:8000 -t 600 -- ./start-local.sh 
    environment:
      - INTEGRATED=1
  backendingress:
    image: hsndocker/backend-local-nginx:latest 
    ports: 
      - "8000:80"
    networks:
      - engineerx
    volumes: 
      - static:/home/app/web/static
      - media:/home/app/web/media
    depends_on:
      - backend
  backend:
    image: hsndocker/backend:latest 
    ports:
      - "8001:8000"
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
       ./wait-for-it.sh db:5432 -- ./start-local.sh 
    environment:
      - POSTGRES_PASSWORD=password
      - FRONTEND_URL=http://127.0.0.1:3000
    networks:
      - engineerx
    volumes: 
      - static:/app/static
      - media:/app/media
    depends_on:
      - db 
  db:
    image: hsndocker/backend-postgres:latest 
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - engineerx 
networks:
  engineerx:
    driver: bridge
volumes:
    static:
      driver: local
    media:
      driver: local